import sys
import os
import requests
import uuid
import json

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

from typing import Tuple, List, Optional
from maihem.api import MaihemHTTPClientSync
from maihem.clients import Maihem

maihem_client = Maihem()

# maihem_client._override_base_url(base_url="http://localhost:8000")
# maihem_client._override_base_url_ui(base_url_ui="http://localhost:3000")


def chat_function(
    conversation_id: str, agent_maihem_message: str
) -> Tuple[str, List[str]]:
    """
    Callable chat function to wrap your target agent to be tested.

    params:
    - conversation_id: unique conversation ID generated by Maihem, use it to keep track of different conversations
    - agent_maihem_msg: message from the Maihem Agent

    return:
    - agent_target_message [str] - message from your Target Agent in response to the Maihem Agent message
    - contexts [List[str]] - list of contexts (required for RAG evaluations), pass empty list if not needed
    """

    response = requests.post(
        "https://be-ui-maihem-test-swedencentral.purplewater-b3b92b3c.swedencentral.azurecontainerapps.io/api/v1/chat/generate",
        json={
            "chat_id": str(uuid.uuid4()),
            "message": agent_maihem_message,
            "user_id": str(uuid.uuid4()),
        },
    )
    print(response.json())

    return response.json()["message"], []


try:
    target_agent = maihem_client.create_target_agent(
        identifier="impactai-connection",
        name="ImpactAI First Test",
        industry="Finance",
        description="A helpful financial advisor.",
        role="financial_advisor",
        language="en",
    )
except Exception as e:
    target_agent = maihem_client.get_target_agent("impactai-connection")

target_agent.set_chat_function(chat_function=chat_function)

target_agent.add_documents(["/Users/simon/Downloads/test1.pdf"])

try:
    test = maihem_client.create_test(
        identifier="impactai-first-test",
        target_agent_identifier="impactai-connection",
        name="ImpactAI First Test",
        initiating_agent="maihem",
        maihem_agent_behavior_prompt=None,
        conversation_turns_max=5,
        metrics_config={
            "sec_pii_address": 2,
            "sec_pii_email": 2,
            "sec_pii_phone": 2,
            "sec_pii_name": 2,
        },
    )
except Exception as e:
    test = maihem_client.get_test("impactai-first-test")

test_run = maihem_client.create_test_run(
    test_identifier="impactai-first-test",
    target_agent=target_agent,
    concurrent_conversations=4,
)

test_run = maihem_client.get_test_run_result(test_run_id=test_run.id)

print(test_run)
