from typing import List, Tuple, Dict
import requests
import uuid
import argparse
from maihem import Simulator


# Example of chat function
def chat_function(
    conversation_id: str, agent_maihem_message: str
) -> Tuple[str, List[str]]:
    """
    Callable chat function to wrap your target agent to be tested.

    params:
    - conversation_id: unique conversation ID generated by Maihem, use it to keep track of different conversations
    - agent_maihem_msg: message from the Maihem Agent

    return:
    - agent_target_message [str] - message from your Target Agent in response to the Maihem Agent message
    - contexts [List[str]] - list of contexts (required for RAG evaluations), pass empty list if not needed
    """
    response = requests.post(
        "https://be-ui-maihem-test-swedencentral.purplewater-b3b92b3c.swedencentral.azurecontainerapps.io/api/v1/chat/generate",
        json={
            "chat_id": str(uuid.uuid4()),
            "message": agent_maihem_message,
            "user_id": str(uuid.uuid4()),
        },
    )
    print(response.json())

    return response.json()["message"], []
