import os
from typing import Dict, List, Tuple
from maihem import Simulator

# Set the Maihem API key as an environment variable
# os.environ['MAIHEM_API_KEY'] = '<YOUR_API_KEY>'

target_agent_identifier = "tg_ag_therapy_1"
test_identifier = "test_1"

# (Optional for RAG testing) list of paths to documents to generate questions from
# documents = ["./docs/doc1.txt", "./docs/doc2.txt"]
documents = None


# Example of chat function
def chat_function(
    conversation_id: str, agent_maihem_message: str, messages: Dict
) -> Tuple[str, List[str], Dict]:
    """
    Callable chat function to wrap your target agent to be tested.

    params:
    - conversation_id: unique conversation ID generated by Maihem, use it to keep track of different conversations
    - agent_maihem_msg: message from the Maihem Agent
    - messages: If needed, object to store history of messages

    return:
    - agent_target_message [str] - message from your Target Agent in response to the Maihem Agent message
    - contexts [List[str]] - list of contexts (required for RAG evaluations), pass empty list if not needed
    """

    # The message from your Target Agent.
    # Connect your agent here to respond to agent_maihem_message.
    # Keep track of same or new conversations with conversation_id
    agent_target_message = "Hi, how can I help you today?"

    # (Optional) List of contexts for RAG evaluations, pass empty list if not needed
    # contexts = ["Context 1", "Context 2"]
    contexts = []

    # (Optional) Dictionary to store history of messages
    # if conversation_id not in messages:
    #     messages[conversation_id] = []
    # messages[conversation_id].append(
    #     {"target": agent_target_message, "maihem": agent_maihem_message}
    # )

    # Delete when you have implemented your chat function
    raise NotImplementedError("Chat function has not been implemented")

    return agent_target_message, contexts


if __name__ == "__main__":

    conversation = Simulator.test(
        chat_function,
        target_agent_identifier=target_agent_identifier,
        test_identifier=test_identifier,
        documents=documents,  # Optional
    )

    print(conversation)
