from typing import List, Tuple
from maihem.simulator import Simulator

# Choose identifier of the target agent, to be defined in config.yaml
target_agent_identifier = "tg_ag_1"

# Choose identifier of the maihem agent, to be defined in config.yaml
maihem_agent_identifier = "mh_ag_1"

# Path to config.yaml
config_path = "./src/config.yaml"

# Example of chat function
def chat_function(conversation_id: str, agent_maihem_message: str) -> Tuple[str, List[str]]:
    """
    Callable chat function to wrap your target agent to be tested.

    params:
    - conversation_id: unique conversation ID generated by Maihem, use it to keep track of different conversations
    - agent_maihem_msg: message from the Maihem Agent

    return:
    - agent_target_message [str] - message from your Target Agent in response to the Maihem Agent message
    - contexts [List[str]] - list of contexts (required for RAG evaluations), pass empty list if not needed
    """
    
    # The message from your Target Agent. 
    # Connect your agent here to respond to agent_maihem_message. 
    # Keep track of same or new conversations with conversation_id
    agent_target_message = "Hi, how can I help you today?"
    
    # List of contexts for RAG evaluations, pass empty list if not needed
    contexts = [] 
    # contexts = ["<Context 1>", "<Context 2>"] 
    
    return agent_target_message, contexts


if __name__ == "__main__":
    
    conversation = Simulator.conversation(
        chat_function, 
        target_agent_identifier, 
        maihem_agent_identifier, 
        config_path
    )
    
    # conversation.messages
    # conversation.evaluations
    
    print(conversation)